### ISSUE TITLE
Support listening for circuit breaker deletion events

### ISSUE THREAD

**Issue by Wuchenwcf** [sentinel-group/sentinel-rust#113]
When the circuit breaker rule is modified or deleted, the circuit breaker may be deleted, and at this time, the application needs to take action on this event

**Comment by Forsworns** [comment]
Sorry for the late response, I didn't check my email recently. This idea is great, my only concern is if this accords with the [Sentinel](https://github.com/alibaba/Sentinel) or [sentinel-golang](https://github.com/alibaba/sentinel-golang). What do you think about the interface in #114 ? @sczyh30 @LearningGp
