### ISSUE TITLE
DefaultMetricSearcher has not implemented the MetricSearcher trait

### ISSUE THREAD

**Issue by flea1lt** [sentinel-group/sentinel-rust#128]
The [MetricSearcher](https://github.com/sentinel-group/sentinel-rust/blob/47057f6f90cb91bdf7cdcf86c0842a8e720c6d25/sentinel-core/src/core/log/metric/mod.rs#L45) trait defines methods' with a return type of `Result<MetricItem>`.

```rust
pub trait MetricSearcher {
    fn find_by_time_and_resource(
        begin_time_ms: u64,
        end_time_ms: u64,
        resource: &str,
    ) -> Result<MetricItem>;
    fn find_from_time_with_max_lines(begin_time_ms: u64, max_lines: u32) -> Result<MetricItem>;
}
```

However return type of [DefaultMetricSearcher](https://github.com/sentinel-group/sentinel-rust/blob/main/sentinel-core/src/core/log/metric/searcher.rs#L50)'s similar methods is `Result<MetricItemVec>`.

```rust
pub fn find_by_time_and_resource(
        &self,
        begin_time_ms: u64,
        end_time_ms: u64,
        resource: String,
    ) -> Result<MetricItemVec> {
        ...
    }

    pub fn find_from_time_with_max_lines(
        &self,
        begin_time_ms: u64,
        max_lines: usize,
    ) -> Result<MetricItemVec> {
        ...
    }
```

`DefaultMetricSearcher` has not implemented the `MetricSearcher` trait. WHY?

Consider modifying the return type of the `MetricSearcher` trait methods to `Result<MetricItemVec>`, aligning with the return type of similar methods in `DefaultMetricSearcher`. Then let `DefaultMetricSearcher` implements `MetricSearcher`.

**Comment by flea1lt** [comment]
PTAL @Forsworns

**Comment by Forsworns** [comment]
Your remark is right, it looks like a typo. This mod is not well tested. You can submit a PR if you'd like to fix it :)
