### ISSUE TITLE
Add middleware for Actix

### ISSUE THREAD

**Issue by sczyh30** [sentinel-group/sentinel-rust#81]
Add Sentinel middleware for [Actix](https://actix.rs/docs/middleware/)

**Comment by Forsworns** [comment]
I just notice this issue, do you work on this? I tried to build the middleware for the general `tower::Service`  these days. The `tonic` uses `tower::Service` as its service abstraction.

Seems Actix shares the same abstraction.

**Comment by sczyh30** [comment]
Contributions are welcome!

**Comment by Forsworns** [comment]
I think we should first make some discussions about #83 and #84 before working on this.
