### ISSUE TITLE
现在rust版本的网关可以用在生产环境吗？有没有相关文档？

### ISSUE THREAD

**Issue by zouhuigang** [sentinel-group/sentinel-rust#82]

**Comment by Forsworns** [comment]
您是说 `examples/proxy/envoy` 吗？目前还不能使用，之后可能会参考 [go 版本的实现](https://github.com/halfrost/sentinel-go-envoy-proxy-wasm/tree/sentinel-go)

或许我应该考虑把它从 example 目录中移除……

**Comment by zouhuigang** [comment]
好的，谢谢
